### ISSUE TITLE
Correct dates validation

### ISSUE THREAD

**Issue by taleon** [aadl/arborcat#140]
Currently, if the schedule pickup form is an old version with mismatching dates, it kicks back a default Drupal message of illegal action. If possible, it would be good to validate that the date option selected is within the options that should be currently available, and if not, kick back to the form saying it needed to be reloaded. This way we can avoid the word illegal coming up in any message which isn't helpful to users.

**Comment by ejk** [comment]
There's a function in drupal core, FormValidator::performRequiredValidation() that checks the submitted value of a select element, and has the message "An illegal choice has been detected. Please contact the site administrator." I'll see if the custom form validation gets run before the core validation.

**Comment by ejk** [comment]
Before I dig too deeply, another solution is to somehow set a timeout that closes or redirects the form if it's open for too long, say 15 minutes. I think a form where the underlying data can change is fair to time out after a bit and make the user reload a fresh version of the form.

**Comment by lauriek334** [comment]
Look like there is a module to add a time limit on form submissions
https://www.drupal.org/project/form_submission_timeout
Do we want to have the user see a countdown time on the form before it is set to inactive?

**Comment by eby** [comment]
I don't think we need a countdown or anything like that. Patrons can submit it anytime as long as it is the same day it was loaded. This is just to deal with how drupal presents the error.

From logs there are a couple ways this seems to happen:

1. They open the form and leave it open in a tab. When they click the link in their email again or manually go back to the old tab they are submitting the form as it loaded days before. Javascript may be able to handle this but not sure it is dependable. Form validation would still be the safest bet.
2. Safari on iphone seems to cache the page pretty hard so when they click a link in the email they are getting an old version of the form that was already in a tab. From logs it has been both unexpected dates and unexpected items. I opened a separate issue about changing the caching #128 to hopefully prevent it but would need to test or see if problem goes away.

Changing the caching might force a browser to refresh when they return to the tab but regardless the form should have validation and good error text about what went wrong.

**Comment by lauriek334** [comment]
Thanks Eby - validation definitely seems the way to go. I did not think we would want to display a countdown timer.

**Comment by ejk** [comment]
Okay, after a few hours of testing and trying different validation function tweaks, I've determined that the core performRequiredValidation() gets run before the form class's own validateForm(), so there's no way to validate and set an custom error on the field if the options are no longer valid.

But maybe we're overthinking it. The validation is doing an important task, making sure the submitted values are actually one of the options that should have been presented to the user. Once the form is reloaded, it should be loaded with valid options for another try. 

If the issue is the text of the error message, we can just override it because it's a translated string. So we could change the text "An illegal choice has been detected. Please contact the site administrator." to something like "A submitted option is no longer valid. Please try again." We can either use one of the built in modules like here: https://www.ostraining.com/blog/drupal/translate-drupal-8-strings/ or we can use the locale_custom_strings_en section of the site's settings.php for a quick override.

**Comment by ejk** [comment]
I did the override in the settings.php on my local dev. Super easy and straightforward. <img width="593" alt="Screen Shot 2020-09-14 at 5 18 46 PM" src="https://user-images.githubusercontent.com/140825/93139269-6c4dc580-f6ae-11ea-9311-bad4bdf4008a.png">

**Comment by ejk** [comment]
Changed text to "There was an error submitting your request. Please try again." in settings.php on production
