### ISSUE TITLE
Cancel Appointments Need to Deal With MeLCat

### ISSUE THREAD

**Issue by eby** [aadl/arborcat#159]
The cancel button currently defaults to 7 days for restoring the shelf expire date:

https://github.com/aadl/arborcat/blob/d93745be2dce26fac827732121578e9a41c5f8fe/templates/pickup-helper-theme.html.twig#L91

However MeLs have a 10 day expire. 

Also, this passing the date as m-d-Y when everything else uses/expects Y-m-d so we should probably change that too.

**Comment by lauriek334** [comment]
Created pull requests in arborcat and aadl front end projects to address the Cancel pickup request button expiry days duration. The calculation for the number of days is now being checked for melcat in order to set the # of expire days correctly.
Also changed the date format to Y-m-d as requested.

https://github.com/aadl/arborcat/pull/160
https://github.com/aadl/aadl.org-frontend/pull/181
